name: flutter_class_project_1
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Doto
      fonts:
        - asset: assets/fonts/Doto-Regular.ttf
        - asset: assets/fonts/Doto-Bold.ttf
        - asset: assets/fonts/Doto-Thin.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Regular.ttf
        - asset: assets/fonts/Caveat-Bold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Tiny5
      fonts:
        - asset: assets/fonts/Tiny5-Regular.ttf
  # assets:
  #   - assets/fonts/
  #   - assets/images/image1.jpg
  #   - assets/images/image2.jpg
  #   - assets/images/image3.jpg